FROM arm32v7/openjdk:slim

MAINTAINER htobenothing
ENV ZOOKEEPER_VERSION 3.4.9

RUN apt-get update && apt-get -y install  unzip wget curl jq net-tools

RUN apt-get update && apt-get -y install wget coreutils gpg

